
# travis config

sudo: required
warnings_are_errors: false

language: r
cache: packages

before_install:
  - R -e "install.packages(c('devtools','roxygen2','testthat', 'drat'))"
  - R -e "drat::addRepo('drat')"
  - R -e "devtools::install_deps('./pkg')"
  - R -e "devtools::document('./pkg')"
  - cd ./pkg

r_packages:
  - rmarkdown

notifications:
  email:
    on_success: change
    on_failure: always 


