#line 2 "scan.c"

#line 4 "scan.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer mc_create_buffer
#define yy_delete_buffer mc_delete_buffer
#define yy_scan_buffer mc_scan_buffer
#define yy_scan_string mc_scan_string
#define yy_scan_bytes mc_scan_bytes
#define yy_init_buffer mc_init_buffer
#define yy_flush_buffer mc_flush_buffer
#define yy_load_buffer_state mc_load_buffer_state
#define yy_switch_to_buffer mc_switch_to_buffer
#define yypush_buffer_state mcpush_buffer_state
#define yypop_buffer_state mcpop_buffer_state
#define yyensure_buffer_stack mcensure_buffer_stack
#define yy_flex_debug mc_flex_debug
#define yyin mcin
#define yyleng mcleng
#define yylex mclex
#define yylineno mclineno
#define yyout mcout
#define yyrestart mcrestart
#define yytext mctext
#define yywrap mcwrap
#define yyalloc mcalloc
#define yyrealloc mcrealloc
#define yyfree mcfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define mc_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer mc_create_buffer
#endif

#ifdef yy_delete_buffer
#define mc_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer mc_delete_buffer
#endif

#ifdef yy_scan_buffer
#define mc_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer mc_scan_buffer
#endif

#ifdef yy_scan_string
#define mc_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string mc_scan_string
#endif

#ifdef yy_scan_bytes
#define mc_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes mc_scan_bytes
#endif

#ifdef yy_init_buffer
#define mc_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer mc_init_buffer
#endif

#ifdef yy_flush_buffer
#define mc_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer mc_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define mc_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state mc_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define mc_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer mc_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define mcpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state mcpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define mcpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state mcpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define mcensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack mcensure_buffer_stack
#endif

#ifdef yylex
#define mclex_ALREADY_DEFINED
#else
#define yylex mclex
#endif

#ifdef yyrestart
#define mcrestart_ALREADY_DEFINED
#else
#define yyrestart mcrestart
#endif

#ifdef yylex_init
#define mclex_init_ALREADY_DEFINED
#else
#define yylex_init mclex_init
#endif

#ifdef yylex_init_extra
#define mclex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra mclex_init_extra
#endif

#ifdef yylex_destroy
#define mclex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy mclex_destroy
#endif

#ifdef yyget_debug
#define mcget_debug_ALREADY_DEFINED
#else
#define yyget_debug mcget_debug
#endif

#ifdef yyset_debug
#define mcset_debug_ALREADY_DEFINED
#else
#define yyset_debug mcset_debug
#endif

#ifdef yyget_extra
#define mcget_extra_ALREADY_DEFINED
#else
#define yyget_extra mcget_extra
#endif

#ifdef yyset_extra
#define mcset_extra_ALREADY_DEFINED
#else
#define yyset_extra mcset_extra
#endif

#ifdef yyget_in
#define mcget_in_ALREADY_DEFINED
#else
#define yyget_in mcget_in
#endif

#ifdef yyset_in
#define mcset_in_ALREADY_DEFINED
#else
#define yyset_in mcset_in
#endif

#ifdef yyget_out
#define mcget_out_ALREADY_DEFINED
#else
#define yyget_out mcget_out
#endif

#ifdef yyset_out
#define mcset_out_ALREADY_DEFINED
#else
#define yyset_out mcset_out
#endif

#ifdef yyget_leng
#define mcget_leng_ALREADY_DEFINED
#else
#define yyget_leng mcget_leng
#endif

#ifdef yyget_text
#define mcget_text_ALREADY_DEFINED
#else
#define yyget_text mcget_text
#endif

#ifdef yyget_lineno
#define mcget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno mcget_lineno
#endif

#ifdef yyset_lineno
#define mcset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno mcset_lineno
#endif

#ifdef yywrap
#define mcwrap_ALREADY_DEFINED
#else
#define yywrap mcwrap
#endif

#ifdef yyalloc
#define mcalloc_ALREADY_DEFINED
#else
#define yyalloc mcalloc
#endif

#ifdef yyrealloc
#define mcrealloc_ALREADY_DEFINED
#else
#define yyrealloc mcrealloc
#endif

#ifdef yyfree
#define mcfree_ALREADY_DEFINED
#else
#define yyfree mcfree
#endif

#ifdef yytext
#define mctext_ALREADY_DEFINED
#else
#define yytext mctext
#endif

#ifdef yyleng
#define mcleng_ALREADY_DEFINED
#else
#define yyleng mcleng
#endif

#ifdef yyin
#define mcin_ALREADY_DEFINED
#else
#define yyin mcin
#endif

#ifdef yyout
#define mcout_ALREADY_DEFINED
#else
#define yyout mcout
#endif

#ifdef yy_flex_debug
#define mc_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug mc_flex_debug
#endif

#ifdef yylineno
#define mclineno_ALREADY_DEFINED
#else
#define yylineno mclineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 47
#define YY_END_OF_BUFFER 48
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[121] =
    {   0,
        0,    0,    2,    2,    9,    9,    0,    0,    0,    0,
       48,   46,   45,   45,   44,   46,   41,   24,   24,   46,
       21,   37,   35,   23,   43,   39,   42,    4,    2,   47,
        4,    9,   10,   15,   16,   15,   19,   20,   19,    0,
        0,   25,   22,    0,    0,    0,    0,    0,    0,   22,
       21,    0,   38,   36,   43,   40,    2,    0,    9,   10,
        0,    0,    0,    0,    0,    0,    5,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   22,    0,   22,
        3,    0,    0,   11,    0,   17,    0,    0,    0,    0,
       33,   27,   26,   29,   28,   34,    0,   31,    0,    0,

        0,    7,    0,    0,   30,   32,   13,    0,    0,    0,
        8,    0,    0,   14,   18,    6,    0,   12,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    6,    7,    1,    8,    9,    1,   10,
       10,   11,   12,   10,   12,   13,   10,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   10,   10,   15,
       16,   17,   18,    8,   19,   20,   21,   22,   23,   24,
       25,   20,   26,   20,   20,   27,   20,   28,   29,   20,
       30,   31,   32,   33,   34,   20,   20,   20,   20,   20,
       10,    1,   10,   35,    8,    1,   36,   20,   37,   38,

       39,   40,   41,   20,   42,   20,   20,   43,   20,   44,
       45,   20,   46,   47,   48,   49,   50,   20,   20,   20,
       20,   20,    1,   51,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    2,    1,    2,    2,    3,    3,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1
    } ;

static const flex_int16_t yy_base[129] =
    {   0,
        0,   51,   17,   19,  102,  153,   21,   23,   24,   26,
      262,  263,  263,  263,  263,   48,  263,  263,  250,  191,
       59,  243,  224,  263,    0,  223,  263,  263,  236,  263,
        0,  209,    0,  263,  263,   52,  263,  263,   53,   53,
       98,  263,  107,    4,    4,  100,  101,   54,   53,  113,
      159,   24,  263,  263,    0,  263,  187,  137,   87,    0,
      101,   61,   97,  107,  100,  113,  263,  153,  153,   75,
       57,   36,   34,   33,   32,  143,   31,  163,   29,   28,
      263,  146,  157,  263,  158,  263,  158,  157,  157,   28,
      263,  263,  263,  263,  263,  263,   27,  263,  162,  161,

      167,  180,  183,  174,  263,  263,  186,  189,  191,  193,
      263,  199,  201,  263,  263,  263,  203,  263,  263,  263,
      242,  245,  248,  251,  254,   36,  257,   34
    } ;

static const flex_int16_t yy_def[129] =
    {   0,
      121,  121,  122,  122,  123,  123,  124,  124,  125,  125,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  126,  120,  120,  120,  120,  120,
      127,  120,  128,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  126,  120,  120,  127,  120,  128,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,    0,
      120,  120,  120,  120,  120,  120,  120,  120
    } ;

static const flex_int16_t yy_nxt[315] =
    {   0,
       12,   13,   14,   13,   15,   12,   16,   12,   17,   18,
       19,   18,   20,   21,   22,   18,   23,   24,   29,   30,
       29,   30,   31,   35,   31,   35,   38,   36,   38,   36,
       39,   69,   39,   70,   26,   79,   60,   80,   55,  106,
      105,   80,   80,   98,   96,   95,   94,   69,   93,   70,
       27,   12,   13,   14,   13,   15,   12,   16,   12,   17,
       18,   19,   18,   20,   21,   22,   18,   23,   24,   92,
       40,   50,   51,   41,   61,   63,   75,   62,   64,   65,
       66,   52,   76,   77,   84,   26,   40,   91,   59,   41,
       61,   63,   75,   62,   64,   65,   66,   52,   76,   77,

       84,   27,   30,   32,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       43,   67,   71,   73,   85,   68,   78,   82,   83,   52,
       86,   87,   72,   74,   88,   52,   30,   67,   71,   73,
       85,   68,   81,   82,   83,   52,   86,   87,   72,   74,
       88,   52,   30,   30,   32,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   50,   51,   89,   90,   97,   78,   99,  100,  101,
      102,   52,  103,  104,  107,   52,  108,   30,   57,   89,
       90,   97,  109,   99,  100,  101,  102,   52,  103,  104,

      107,   52,  108,   30,   43,  110,  111,  112,  109,   44,
       59,  113,  114,   45,  115,   46,  116,   47,   48,   49,
      117,  110,  111,  112,  118,  119,   44,  113,  114,   45,
      115,   46,  116,   47,   48,   49,  117,   57,   56,   54,
      118,  119,   25,   25,   25,   28,   28,   28,   33,   33,
       33,   34,   34,   34,   37,   37,   37,   58,   53,   58,
       42,  120,   11,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120
    } ;

static const flex_int16_t yy_chk[315] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    3,    7,    4,    8,    9,    7,   10,    8,
        9,   44,   10,   45,    1,   52,  128,   52,  126,   97,
       90,   80,   79,   77,   75,   74,   73,   44,   72,   45,
        1,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,   71,
       16,   21,   21,   16,   36,   39,   48,   36,   39,   40,
       40,   21,   48,   49,   62,    2,   16,   70,   59,   16,
       36,   39,   48,   36,   39,   40,   40,   21,   48,   49,

       62,    2,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
       43,   41,   46,   47,   63,   41,   50,   61,   61,   43,
       64,   65,   46,   47,   66,   50,    5,   41,   46,   47,
       63,   41,   58,   61,   61,   43,   64,   65,   46,   47,
       66,   50,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,   51,   51,   68,   69,   76,   78,   82,   83,   85,
       87,   51,   88,   89,   99,   78,  100,    6,   57,   68,
       69,   76,  101,   82,   83,   85,   87,   51,   88,   89,

       99,   78,  100,    6,   20,  102,  103,  104,  101,   20,
       32,  107,  108,   20,  109,   20,  110,   20,   20,   20,
      112,  102,  103,  104,  113,  117,   20,  107,  108,   20,
      109,   20,  110,   20,   20,   20,  112,   29,   26,   23,
      113,  117,  121,  121,  121,  122,  122,  122,  123,  123,
      123,  124,  124,  124,  125,  125,  125,  127,   22,  127,
       19,   11,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,

      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,  120
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex_yacc/scan.l"
/*
 * lexical analyzer for xpc
 */
#line 6 "lex_yacc/scan.l"

#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <Rinternals.h>

#include "symbol.h"
#include "ecode.h"
#include "mcinit.h"
#include "util.h"
#include "mchdr.h"
#include "fname.h"
#include "flags.h"
#include "xpcdef.h"
#include "xpctab.h"

#define MAX_INCLUDE_DEPTH 10
#define MAXLINE 2000

static void    open_buffer(char *filename);
static void    close_buffer(void);
static void    close_preproc_file(void);
static void    get_comment ( void );
static char*   get_includefile ( void );
static int     mcgetc(void);

typedef struct _selem {
    FILE   *fin;
    char   *filename;
    char   *dirname;
    char   *buf;
    char   *bufp;
    size_t line_number;
} include_stack_elem ;

static include_stack_elem include_stack[MAX_INCLUDE_DEPTH + 1];

static FILE *fin  = NULL;              /* input  stream */
static int write_preproc_file = 0;
static FILE *fp_preproc = NULL;  /* output stream for preprocessed file */
static char *filename;
static char *dirname;
static char *buf;
static char *bufp;
static int include_level = -1;
static unsigned int line_number;
static size_t if_nest_cnt; /* number of nested #if constructs within a #if */

/*
 * for MKS Lex
 */

#undef  YY_INTERACTIVE
#define YY_INTERACTIVE 0

/*
 * the following is needed
 * to make flex not use isatty and fileno
 * which gave errors in fcc (Fujitsu C compiler in Lahey)
 */

#define YY_NEVER_INTERACTIVE 1

#define YY_FATAL_ERROR(msg) error(msg)

/*
 * Flex needs this
 * MKS Lex doesn't and just ignores this
 * but do use the special Flex scanner macro
 */

#ifdef FLEX_SCANNER

#define YY_INPUT(buf,result,max_size) \
{\
	int c = mcgetc(); \
	result = (c == EOF) ? YY_NULL : (buf[0] = c, 1); \
}

#endif

#line 899 "scan.c"
/* the "incl" state is used for picking up the name of an include file
 */

#line 903 "scan.c"

#define INITIAL 0
#define incl 1
#define get_flag 2
#define goto_else 3
#define goto_endif 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 109 "lex_yacc/scan.l"


#line 1127 "scan.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 121 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 263 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 111 "lex_yacc/scan.l"
BEGIN(incl);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "lex_yacc/scan.l"
/* eat white space */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 113 "lex_yacc/scan.l"
{   
                    char *inclname = get_includefile();
                    if (inclname != NULL) {
                        open_buffer(inclname);
                    } 
                    BEGIN(INITIAL);
                 }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 120 "lex_yacc/scan.l"
{ mcerror("Illegal #include syntax");
                BEGIN(INITIAL);
              }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 124 "lex_yacc/scan.l"
BEGIN(get_flag);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 125 "lex_yacc/scan.l"
{if_nest_cnt = 0;
                    BEGIN(goto_endif);
                   }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 128 "lex_yacc/scan.l"
{if_nest_cnt = 0;
                    BEGIN(goto_endif);
                   }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 131 "lex_yacc/scan.l"
/* ignore */
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 133 "lex_yacc/scan.l"
/* eat the white space */
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 134 "lex_yacc/scan.l"
{  if (flag_present(mctext)) {
		   	BEGIN(INITIAL);
                      } else {
                        if_nest_cnt = 0;
			BEGIN(goto_else);
                      }
                   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 142 "lex_yacc/scan.l"
{if_nest_cnt++;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 143 "lex_yacc/scan.l"
{if (!if_nest_cnt) BEGIN(get_flag);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 144 "lex_yacc/scan.l"
{if (!if_nest_cnt) BEGIN(INITIAL);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 145 "lex_yacc/scan.l"
{  if (!if_nest_cnt) {
                            BEGIN(INITIAL);
                        } else {
                          if_nest_cnt--;
                        }
                     }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 151 "lex_yacc/scan.l"
/* skip */
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 152 "lex_yacc/scan.l"
/* skip newline */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 154 "lex_yacc/scan.l"
{if_nest_cnt++;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 155 "lex_yacc/scan.l"
{  if (!if_nest_cnt) { 
                             BEGIN(INITIAL);
                         } else {
                            if_nest_cnt--;
                         }
                      }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 161 "lex_yacc/scan.l"
/* skip */
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 162 "lex_yacc/scan.l"
/* skip newline */
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(get_flag):
case YY_STATE_EOF(goto_else):
case YY_STATE_EOF(goto_endif):
#line 165 "lex_yacc/scan.l"
{ close_buffer(); 
          if (include_level < 0) {
            close_preproc_file();
            yyterminate();
          }
        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 172 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); mclval.ival = strtol(mctext, NULL, 10); return T_INTNUM; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); mclval.dval = strtod(mctext, NULL)    ; return T_NUMBER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 175 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); get_comment();}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 177 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = mctext[0]; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 179 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_POW; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 180 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_GT;  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 181 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_GE;  }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 182 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_LT;  }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 183 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_LE;  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 184 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_AND; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 185 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_OR;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 186 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_NOT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 187 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_EQ;  }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 188 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_NE;  }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 190 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_GT;  }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 191 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_GE;  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 192 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_LT;  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 193 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_LE;  }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 194 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_NOT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 195 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_NE;  }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 196 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_AND; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 197 "lex_yacc/scan.l"
{if (write_preproc_file) fputs(mctext, fp_preproc); return mclval.ival = T_OR;  }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 199 "lex_yacc/scan.l"
{       if (write_preproc_file) fputs(mctext, fp_preproc);
                Symbol *sp;

                /*
                 * lookup symbol and if it does not exist
                 * then give it type T_NAME 
                 */

                sp = sym_create(Stp, (char *) mctext, T_NAME);

                mclval.sp = sp;

                return sp->type;
        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 214 "lex_yacc/scan.l"
; /* skip carriage return 
                 * Do not write \r (carriage return) to the preproc file.
                 * On Windows, a \r is automatically added for every \n when the
                 * file is written, so if we would write a \r the result would be
                 * \r\r\n.
                 */
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 220 "lex_yacc/scan.l"
if (write_preproc_file) fputs(mctext, fp_preproc);
	YY_BREAK
/* skip other whitespace and newline */
case 46:
YY_RULE_SETUP
#line 224 "lex_yacc/scan.l"
{if (!scanning) mcerror( "Illegal character in input" );}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 227 "lex_yacc/scan.l"
ECHO;
	YY_BREAK
#line 1482 "scan.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 121 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 121 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 120);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 227 "lex_yacc/scan.l"


int mcwrap(void) {
  return 1;
}

void init_scanner(char *filenm, const char *filenm_preproc) {
   /*
    * Initialise the scanner for the specified filename 
    */

   include_level = -1;

   open_buffer(filenm);

   write_preproc_file = filenm_preproc != NULL;
   if (write_preproc_file) fp_preproc = fopen(filenm_preproc, "w+");
}

void close_preproc_file(void) {
    if (write_preproc_file) {
      fclose(fp_preproc);
      write_preproc_file = 0;
    }
}

void reset_scanner(void) {
    /*
     * Close all buffers. This function is called when an
     * end; statement has occurred in the model
     */

    if (write_preproc_file) {
      // write a newline, the newline after end; in the input is ignored
      fputc('\n', fp_preproc);
      close_preproc_file();
    }


    if (include_level > 0) {
      mcerror("end; statement not allowed in included file");
    }

    /* first close current buffer (the current buffer is not stored on 
     * the stack) */
    close_buffer();

    if (include_level == -1) return;

    /* close buffers on the stack */
    int i;
    for (i = 0; i <= include_level; i++) {
        fclose(include_stack[i].fin);
        if (i > 0) {
          /* filename was allocated with malloc in get_includefile(). */
          free(include_stack[i].filename);
        }
        free(include_stack[i].dirname);
        free(include_stack[i].buf);
    }

    include_level = -1;

}


void open_buffer(char *new_filename) {   

    /*
     * open a new buffer for reading from the specified filename
     */

    if (include_level >= 0) {
	/*
         * save current buffer information on stack
         */
        include_stack[include_level].fin         = fin;
        include_stack[include_level].filename    = filename;
        include_stack[include_level].dirname     = dirname;
        include_stack[include_level].buf         = buf;
        include_stack[include_level].bufp        = bufp;
        include_stack[include_level].line_number = line_number;

       
    }

    if (++include_level > MAX_INCLUDE_DEPTH) {
        mcerror("Includes nested too deeply. Maximum include depth %d.", 
                MAX_INCLUDE_DEPTH);
        return;
    }

    /* create a new buffer */
    filename = new_filename;
    dirname = get_path_name(filename);
    fin = efopen( filename, "r" );
    buf = emalloc(MAXLINE + 1);
    buf[0] = 0;
    bufp = buf;
    line_number = 0;

    /* The first path to be searched for include files should be the
     * directory of the current include file */
    set_standard_path(dirname);
}

static void close_buffer(void) {

   /* Closes the current buffer */

    fclose(fin);
    free(buf);
    bufp = NULL;
    if (include_level > 0) {
        /* filename was allocated with malloc in get_includefile(). */
	free(filename);
    }
    free(dirname);
    
    if (--include_level >= 0) {	
        /* restore previous buffer information */

        fin         = include_stack[include_level].fin;
        filename    = include_stack[include_level].filename;
        dirname     = include_stack[include_level].dirname;
        buf         = include_stack[include_level].buf;
        bufp        = include_stack[include_level].bufp;
        line_number = include_stack[include_level].line_number;

	/* make directory of current file the first directory to be searched
         * for include files */ 
        set_standard_path(dirname);
    } 
}

static int mcgetc(void)
{   
     /* return next char from current buffer
     * or EOF
     */

    int     c;
    char    *pn;

    if( bufp == NULL)
        return EOF;

    if( *bufp == 0 )
    {
        if( (bufp = fgets(buf, MAXLINE-2, fin)) == NULL )
            return EOF;
        else if( (pn = strchr(bufp, '\n')) == NULL )
//            warning("Line too long and split\n");

        /*
         * remove any \r at end
         */

        if( pn && pn > bufp && *(pn-1) == '\r' )
        {
            *(pn-1) = '\n';
            *pn     = '\0';
        }

        ++line_number;
    }

    c = *bufp++;
    return c;
}

void showbuf( FILE *fout )
{
    char    *p   = buf;
    char    *end = bufp ? bufp : strchr(buf,'\n') - 1;
    int pos = 0;

    for( ; *p && p < end ; p++)
    {
        if( *p == '\t')
            pos += 8 - (pos % 8);
        else
            pos++;
    }

    if( line_number ) 
        (void) fprintf(fout,"Line: %u of file %s\n", line_number, filename);
    fprintf(fout, "%s", buf);
    fprintf(fout, "%*s\n", pos, "^" );
}


/*
 * read comment
 * and discard to end of line
 */

static void get_comment(void) {
    int c;
    while ((c = input()) != '\n' && c != EOF) {
       /* Do not write \r (carriage return) to the preproc file.
        * On Windows, a \r is automatically added for every \n when the
        * file is written, so if we would write a \r the result would be
        * \r\r\n.
        */
       if (write_preproc_file && c != '\r') fputc((char) c, fp_preproc);
    }
    if (write_preproc_file) fputc('\n', fp_preproc);
}

static char * get_includefile(void) {
   /* Returns the name of the include file based on the specified
    * include filename and the include search paths
    */

   /* remove the quotes from mctext */
   char *includefile;
   int len = strlen(mctext) - 2;
   char *includename = emalloc(len + 1);
   includename = strncpy(includename, mctext + 1, len);
   *(includename + len) = 0;

   /* search for the include file based on the include search paths */
   includefile = get_includefilename(includename);
   if (includefile == NULL) {
       mcerror("Include file %s not found", includename);
   }
   free(includename);
   return includefile;
}

