library(regts)
library(isismdl)

islm_model <- IsisMdl$new("demo/islm.mif")
islm_model$set_mws(islm_input_mws)
ca_data <- regts(matrix(2, ncol = 2), start = "2015Q2", end =  "2015Q4",
              names = c("c", "x"))
islm_model$set_ca(ca_data)
islm_model$solve("2015Q2/2015Q4")
print(islm_model$get_data())
print(islm_model$get_ca_names())
print(islm_model$get_ca())
print(islm_model$get_ca(period = "2015Q2/2016Q3"))
print(islm_model$get_ca("c"))
print(islm_model$get_ca("x"))

mws <- islm_model$get_mws()
print(mws)
islm_model <- IsisMdl$new("demo/islm.mif")
islm_model$set_mws(mws)
islm_model$solve()
print(islm_model$get_ca())
