library(regts)
library(isismdl)

islm_model <- IsisMdl$new("demo/islm.mif")
islm_model$set_mws(islm_input_mws)
y <- regts(985, start = "2015Q2")
r <- regts(c(3.5, 3.6), start = "2015Q2")
fit <- cbind(y, r) 
islm_model$set_fit(fit)
print(islm_model$get_fit())
rms_values <- list(c = 5, i = 21, md = 2, t = 2)
islm_model$set_rms(rms_values)
islm_model$set_solve_options(report = "period")
islm_model$set_fit_options(report = "mininal")
islm_model$solve()
print(islm_model$get_data())
print(islm_model$get_ca())
