library(regts)
library(isismdl)
islm_model <- IsisMdl$new("demo/islm.mif")
islm_model$set_solve_options(list(report = "none"))
print(islm_model$get_solve_options())
#islm_model$set_mws(islm_input_mws)
islm_model$set_period("2010Q2/2011Q2")
islm_model$solve()
