library(regts)
library(isismdl)
islm_model <- IsisMdl$new("demo/islm.mif")
islm_model$set_mws(islm_input_mws)
islm_model$set_cvgcrit(1e-30, vars = "y")
print(islm_model$get_cvgcrit())
mws <- islm_model$get_mws()
print(mws$cvgcrit)
print(islm_input_mws$cvgcrit)
islm_model$set_mws(islm_input_mws)
islm_model$set_mws(mws)
print(islm_model$get_cvgcrit())
