library(regts)
library(isismdl)
islm_model <- IsisMdl$new("demo/islm.mif")
print(islm_model$get_variable_names())
print(islm_model$get_variable_names("i|c"))
print(islm_model$get_variable_names(vtype = "all"))
print(islm_model$get_variable_names(vtype = "allfrml"))
quit()
islm_model$set_mws(islm_input_mws)
islm_model$set_cvgcrit(1e-5, pattern = "c|i")
print(islm_model$get_cvgcrit())
quit()
islm_model$solve()
