\MethodStart
\Method{get\_period}{getUperiod}{}
%
\index{get\_period@\Methodname{get\_period}}%

\Description
Returns the model period

\Usage

\begin{usage}
mdl$get_data_period()
\end{usage}

\Value

A \Classname{regperiod\_range} object

\Examples
<<! get_period >>=
mdl$get_period()
@

\Seealso
\hyperlink{HUgetUdataUperiod}{\Methodname{get\_data\_period}}\\
\hyperlink{HUsetUperiod}{\Methodname{set\_period}}
