#' Reads a model from a model information file
#'
#' This function reads a model from a model information (mif) file
#' that has been generated by function \code{\link{compile_mdl}}
#' @param mif_file the full path of the mif file
#' @return a \code{\link{IsisMdl}} object
#' @export
read_mdl <- function(mif_file) {
    return (IsisMdl$new(mif_file))
}
